@startuml "Container"

!include ./C4-PlantUML/C4_Container.puml
!include ./Context.puml

LAYOUT_WITH_LEGEND()

System_Boundary(JudgeApi, "JudgeApi") {
    Container(ApiScript, "Script", "爬蟲")
    ContainerDb(ApiDB, "API Database", "", "題目資料")

    Rel(ApiScript, ApiDB, "交互")
    Rel(ApiServer, ApiDB, "交互")
    Rel_L(ApiScript, Judge, "爬蟲")
}



System_Boundary(JudgeBox, "JudgeBox") {
    System_Boundary(Backend, "Backend") {
        Container(WebServer, "Web Server")
        ContainerDb(DB, "Database")
        ContainerDb(UserDB, "User Database", "處理用戶登入")
        Rel(WebServer, DB, "交互")
        Rel(WebServer, UserDB, "交互")
    }
    Rel_U(WebServer, Frontend, "交互")
    Rel_R(Extension, Frontend, "交互")
}
Rel(WebServer, ApiServer, "題目資料", "http request")

@enduml